# Generated by Django 4.2.11 on 2026-04-23 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=2, help_text='Max new conversations per day. 0 = unlimited.')),
                ('monthly_limit', models.PositiveIntegerField(default=30, help_text='Max new conversations per month. 0 = unlimited.')),
                ('daily_used', models.PositiveIntegerField(default=0)),
                ('monthly_used', models.PositiveIntegerField(default=0)),
                ('last_daily_reset', models.DateField(default=django.utils.timezone.now)),
                ('last_monthly_reset', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Quota',
                'verbose_name_plural': 'Usage Quotas',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('conversation_created', 'Conversation created'), ('conversation_deleted', 'Conversation deleted')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
