# Generated by Django 4.2.11 on 2026-04-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', help_text='User-editable name for this conversation.', max_length=100),
        ),
    ]
